language: node_js
node_js: 
  - 16.13

sudo: required

cache: npm

services:
  - mysql

install:
  - npm ci

before_script:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('password') where User='root'; FLUSH PRIVILEGES;"
  - sudo mysql -u root -ppassword -e 'CREATE DATABASE 390db;'
  - sudo mysql -u root -ppassword 390db < test/travis.sql

script:
  - cd server
  - npm i
  - cd .. 
  - cd client
  - npm i
  - cd src
  - cd __tests__
  - npm citest API_methods.test.js 




deploy:
  provider: pages
  local_dir: build
  on:
    branch: main


