language: node_js
node_js: 
  - 16.13



cache: npm

services:
  - mysql

install:
  - npm ci

before_script:
  - mysql -u root -proot -e 'CREATE DATABASE 390db;'
  - mysql -u root -proot 390db < test/travis.sql

script:
  - cd server
  - npm i
  - cd .. 
  - cd client
  - npm i
  - cd src
  - npm test API_methods.test.js


deploy:
  provider: pages
  local_dir: build
  on:
    branch: main

