language: node_js
node_js: 
  - 16.13

sudo: required


cache: npm

services:
  - mysql

install:
  - npm ci

before_script:
  - sudo mysql -u root -p -e 'CREATE DATABASE 390db;'
  - sudo mysql -u root -p 390db < test/travis.sql

script:
  - cd server
  - npm i
  - cd .. 
  - cd client
  - npm i
  - cd src
  - npm test API_methods.test.js


deploy:
  provider: pages
  local_dir: build
  on:
    branch: main

