language: node_js
node_js: 
  - 16.13


cache: npm

services:
  - mysql

before_install: 
  - mysql -u travis --password="" < test/travis.sql

install:
  - npm ci

script:
  - cd client
  - cd src
  - npm test


deploy:
  provider: pages
  local_dir: build
  on:
    branch: main

