language: node_js
node_js: 
  - 16.13

sudo: required


cache: npm

services:
  - mysql

install:
  - npm ci

before_script:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade
  - sudo service mysql restart
  - mysql -u root -e 'CREATE DATABASE 390db;'
  - mysql -u root 390db < test/travis.sql

script:
  - cd server
  - npm i
  - cd .. 
  - cd client
  - npm i
  - cd src
  - npm test API_methods.test.js


deploy:
  provider: pages
  local_dir: build
  on:
    branch: main

