language: node_js
node_js: 
  - 16.13


cache: npm

before_install: 
  - mysql -e 'CREATE DATABASE 390db;'

install:
  - npm ci

script:
  - cd client
  - npm i
  - cd .. 
  - cd server
  - npm i
  - cd ..
  - cd client
  - cd src
  - npm test

services:
  - mysql

deploy:
  provider: pages
  local_dir: build
  on:
    branch: main

