runtime: nodejs14

env: standard

env_variables:
#  SQL_USER: root
 # SQL_PASSWORD: root
#  SQL_DATABASE: cloudscratch
  # e.g. my-awesome-project:us-central1:my-cloud-sql-instance
 # INSTANCE_CONNECTION_NAME: sunlit-form-338718:northamerica-northeast1:sql-scratch-pw-root
# [END gae_mysql_env]

handlers:
  - url: /.*
    script: auto

beta_settings:
 # cloud_sql_instances: sunlit-form-338718:northamerica-northeast1:sql-scratch-pw-root